apiVersion: v1
items:
- apiVersion: agents.x-k8s.io/v1alpha1
  kind: Sandbox
  metadata:
    annotations:
      agents.x-k8s.io/pod-name: pr387-flow2-x5qtm
      agents.x-k8s.io/sandbox-template-ref: pr387-flow2
    creationTimestamp: "2026-06-25T09:03:54Z"
    generateName: pr387-flow2-
    generation: 1
    labels:
      agents.x-k8s.io/sandbox-pod-template-hash: 2e857812
      agents.x-k8s.io/sandbox-template-ref-hash: dc60806a
      agents.x-k8s.io/warm-pool-sandbox: dc60806a
    name: pr387-flow2-x5qtm
    namespace: agentcube-flow-test
    ownerReferences:
    - apiVersion: extensions.agents.x-k8s.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: SandboxWarmPool
      name: pr387-flow2
      uid: 7f3a44f7-6ab1-48e1-a903-f3b999bfcfe3
    resourceVersion: "1058"
    uid: d7d81d4d-0f09-45d3-9d41-ceb28f34bd10
  spec:
    podTemplate:
      metadata:
        labels:
          agents.x-k8s.io/sandbox-pod-template-hash: 2e857812
          agents.x-k8s.io/sandbox-template-ref-hash: dc60806a
          agents.x-k8s.io/warm-pool-sandbox: dc60806a
          app: pr387-flow2
          test.agentcube.io/flow: pr387
      spec:
        automountServiceAccountToken: false
        containers:
        - args:
          - --workspace=/root
          env:
          - name: PICOD_AUTH_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                key: public.pem
                name: picod-router-identity
          image: picod:latest
          imagePullPolicy: IfNotPresent
          name: codeinterpreter
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
    replicas: 1
    shutdownPolicy: Retain
  status:
    conditions:
    - lastTransitionTime: "2026-06-25T09:03:55Z"
      message: Pod is Ready
      observedGeneration: 1
      reason: DependenciesReady
      status: "True"
      type: Ready
    podIPs:
    - 10.42.0.10
    replicas: 1
    selector: agents.x-k8s.io/sandbox-name-hash=93893b4a
- apiVersion: agents.x-k8s.io/v1alpha1
  kind: Sandbox
  metadata:
    annotations:
      agents.x-k8s.io/pod-name: pr387-flow2-xx7dt
      agents.x-k8s.io/sandbox-template-ref: pr387-flow2
    creationTimestamp: "2026-06-25T09:04:41Z"
    generateName: pr387-flow2-
    generation: 1
    labels:
      agents.x-k8s.io/sandbox-pod-template-hash: 2e857812
      agents.x-k8s.io/sandbox-template-ref-hash: dc60806a
      agents.x-k8s.io/warm-pool-sandbox: dc60806a
    name: pr387-flow2-xx7dt
    namespace: agentcube-flow-test
    ownerReferences:
    - apiVersion: extensions.agents.x-k8s.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: SandboxWarmPool
      name: pr387-flow2
      uid: 7f3a44f7-6ab1-48e1-a903-f3b999bfcfe3
    resourceVersion: "1119"
    uid: 19b759ee-a61d-4c23-96c8-d93867f00786
  spec:
    podTemplate:
      metadata:
        labels:
          agents.x-k8s.io/sandbox-pod-template-hash: 2e857812
          agents.x-k8s.io/sandbox-template-ref-hash: dc60806a
          agents.x-k8s.io/warm-pool-sandbox: dc60806a
          app: pr387-flow2
          test.agentcube.io/flow: pr387
      spec:
        automountServiceAccountToken: false
        containers:
        - args:
          - --workspace=/root
          env:
          - name: PICOD_AUTH_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                key: public.pem
                name: picod-router-identity
          image: picod:latest
          imagePullPolicy: IfNotPresent
          name: codeinterpreter
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
    replicas: 1
    shutdownPolicy: Retain
  status:
    conditions:
    - lastTransitionTime: "2026-06-25T09:04:42Z"
      message: Pod is Ready
      observedGeneration: 1
      reason: DependenciesReady
      status: "True"
      type: Ready
    podIPs:
    - 10.42.0.11
    replicas: 1
    selector: agents.x-k8s.io/sandbox-name-hash=59dcf63e
- apiVersion: extensions.agents.x-k8s.io/v1alpha1
  kind: SandboxWarmPool
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"extensions.agents.x-k8s.io/v1alpha1","kind":"SandboxWarmPool","metadata":{"annotations":{},"name":"pr387-flow2","namespace":"agentcube-flow-test"},"spec":{"replicas":2,"sandboxTemplateRef":{"name":"pr387-flow2"}}}
    creationTimestamp: "2026-06-25T09:03:54Z"
    generation: 1
    name: pr387-flow2
    namespace: agentcube-flow-test
    resourceVersion: "1120"
    uid: 7f3a44f7-6ab1-48e1-a903-f3b999bfcfe3
  spec:
    replicas: 2
    sandboxTemplateRef:
      name: pr387-flow2
  status:
    readyReplicas: 2
    replicas: 2
    selector: agents.x-k8s.io/warm-pool-sandbox=dc60806a
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      agents.x-k8s.io/propagated-labels: agents.x-k8s.io/sandbox-pod-template-hash,agents.x-k8s.io/sandbox-template-ref-hash,agents.x-k8s.io/warm-pool-sandbox,app,test.agentcube.io/flow
    creationTimestamp: "2026-06-25T09:03:54Z"
    labels:
      agents.x-k8s.io/sandbox-name-hash: 93893b4a
      agents.x-k8s.io/sandbox-pod-template-hash: 2e857812
      agents.x-k8s.io/sandbox-template-ref-hash: dc60806a
      agents.x-k8s.io/warm-pool-sandbox: dc60806a
      app: pr387-flow2
      test.agentcube.io/flow: pr387
    name: pr387-flow2-x5qtm
    namespace: agentcube-flow-test
    ownerReferences:
    - apiVersion: agents.x-k8s.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Sandbox
      name: pr387-flow2-x5qtm
      uid: d7d81d4d-0f09-45d3-9d41-ceb28f34bd10
    resourceVersion: "1056"
    uid: 556854eb-39c1-47b6-93c8-e63341ba7e8c
  spec:
    automountServiceAccountToken: false
    containers:
    - args:
      - --workspace=/root
      env:
      - name: PICOD_AUTH_PUBLIC_KEY
        valueFrom:
          secretKeyRef:
            key: public.pem
            name: picod-router-identity
      image: picod:latest
      imagePullPolicy: IfNotPresent
      name: codeinterpreter
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: k3d-agentcube-flow-v046-server-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:03:55Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:03:54Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:03:55Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:03:55Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:03:54Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://7bd8a420a7c96d7a0c54a0c85a559681f095f90c0227faeda297c3b7c2149cb2
      image: docker.io/library/picod:latest
      imageID: sha256:7499d9f90ab288da55b18a49f603237240dcd75493e290b38fc2eaf811281944
      lastState: {}
      name: codeinterpreter
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-25T09:03:55Z"
    hostIP: 172.20.0.2
    hostIPs:
    - ip: 172.20.0.2
    phase: Running
    podIP: 10.42.0.10
    podIPs:
    - ip: 10.42.0.10
    qosClass: Burstable
    startTime: "2026-06-25T09:03:54Z"
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      agents.x-k8s.io/propagated-labels: agents.x-k8s.io/sandbox-pod-template-hash,agents.x-k8s.io/sandbox-template-ref-hash,agents.x-k8s.io/warm-pool-sandbox,app,test.agentcube.io/flow
    creationTimestamp: "2026-06-25T09:04:41Z"
    labels:
      agents.x-k8s.io/sandbox-name-hash: 59dcf63e
      agents.x-k8s.io/sandbox-pod-template-hash: 2e857812
      agents.x-k8s.io/sandbox-template-ref-hash: dc60806a
      agents.x-k8s.io/warm-pool-sandbox: dc60806a
      app: pr387-flow2
      test.agentcube.io/flow: pr387
    name: pr387-flow2-xx7dt
    namespace: agentcube-flow-test
    ownerReferences:
    - apiVersion: agents.x-k8s.io/v1alpha1
      blockOwnerDeletion: true
      controller: true
      kind: Sandbox
      name: pr387-flow2-xx7dt
      uid: 19b759ee-a61d-4c23-96c8-d93867f00786
    resourceVersion: "1118"
    uid: 2e62c0ef-8fa3-4df1-983e-c5dbd9d5d45b
  spec:
    automountServiceAccountToken: false
    containers:
    - args:
      - --workspace=/root
      env:
      - name: PICOD_AUTH_PUBLIC_KEY
        valueFrom:
          secretKeyRef:
            key: public.pem
            name: picod-router-identity
      image: picod:latest
      imagePullPolicy: IfNotPresent
      name: codeinterpreter
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 32Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: k3d-agentcube-flow-v046-server-0
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:04:42Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:04:41Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:04:42Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:04:42Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-06-25T09:04:41Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://23ab870129df3a65335a00280d981956c67727b9039299c16cd4674de67ca049
      image: docker.io/library/picod:latest
      imageID: sha256:7499d9f90ab288da55b18a49f603237240dcd75493e290b38fc2eaf811281944
      lastState: {}
      name: codeinterpreter
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-06-25T09:04:41Z"
    hostIP: 172.20.0.2
    hostIPs:
    - ip: 172.20.0.2
    phase: Running
    podIP: 10.42.0.11
    podIPs:
    - ip: 10.42.0.11
    qosClass: Burstable
    startTime: "2026-06-25T09:04:41Z"
kind: List
metadata:
  resourceVersion: ""
